### ISSUE TITLE
Consultation on multiple groups

### ISSUE THREAD

**Issue by UruCraft78** [YouHaveTrouble/CommandWhitelist#100]
Hello, very good, I have a question, I have not found information on the different pages of the plugin.
It is possible to add several groups to divide the commands that will be shown in the /?
As an example, I don't want the /gamemode to be shown to the users, but the builder, I'll leave the config to see if it's configured correctly.
I appreciate the help
use_protocollib: false
message_type: CHAT
groups:
builder:
commands:
- gamemode
- fly
subcommands:
- gamemode spectator
- gamemode adventure
moderador:
commands:
- gamemode
- kick
- invsee
- tp
- mute
- tphere
- vanish
subcommands:
- gamemode creative
- gamemode adventure
default:
commands:
- login
- register
- spawn
- home
- sethome
- delhome
- homes
- ps
- jobs
- tpa
- tpr
- tpaccept
- tpacancel
- tpdeny
- balancetop
- asb
- tc
- autotool
- back
- qa
- backpack
- chestsort
- skin
- kit
- helpop
- msg
- msgtoggle
- pay
- warp
- warps
- hat
- fly
- chatgames
- gamemode
subcommands:
- ps addowner
- ps removeowner
- tc help
- pay *
- pay **
- backpack open
- backpack help
- backpack shortcut
- skin clear
- skin favorite
- skin favorites
- skin help
- skin history
- skin random
- skin search
- skin undo

**Comment by 0elek** [comment]
Like this. You can define as many groups as you want
```
groups:
  default:
    commands:
    - msg
    - warp
    subcommands:
    - help about
  example:
    commands:
    - icarus
    subcommands:
    - d story
  you_can_call_it_anything:
    commands:
    - some_test
    subcommands:

```
Then use `commandwhitelist.group.<group_name>` permission.
