### ISSUE TITLE
All commands with ":" are usable if you have protocollib:true

### ISSUE THREAD

**Issue by msmanui** [YouHaveTrouble/CommandWhitelist#84]
So alias does not work if you dont have protocollib: true, but if i enable it, then all commands return value like if you do /lp, it will return, even its not on the command list. It does not autocomplete but they return value if you execute the command.  The only way to fix is using protocollib: false, but i wont be able to use alias

```
alias:
  command: /bs
  type: ALIAS
  alias: /essentials:disposal
  permission-required: false
  register: true
```
